# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.WellKnownOpenidConfigurationGet200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :href,
    :clientId,
    :scopes
  ]

  @type t :: %__MODULE__{
    :href => String.t | nil,
    :clientId => String.t | nil,
    :scopes => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

