# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BackupRestoreRequest do
  @moduledoc """
  Request body for restoring a backup for a set of classes
  """

  @derive Jason.Encoder
  defstruct [
    :config,
    :include,
    :exclude,
    :node_mapping
  ]

  @type t :: %__MODULE__{
    :config => Weaviate.Model.RestoreConfig.t | nil,
    :include => [String.t] | nil,
    :exclude => [String.t] | nil,
    :node_mapping => %{optional(String.t) => String.t} | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:config, :struct, Weaviate.Model.RestoreConfig)
  end
end

