# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BackupCreateResponse do
  @moduledoc """
  The definition of a backup create response body
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :classes,
    :backend,
    :path,
    :error,
    :status
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :classes => [String.t] | nil,
    :backend => String.t | nil,
    :path => String.t | nil,
    :error => String.t | nil,
    :status => String.t | nil
  }

  def decode(value) do
    value
  end
end

