# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BatchStats do
  @moduledoc """
  The summary of a nodes batch queue congestion status.
  """

  @derive Jason.Encoder
  defstruct [
    :queueLength,
    :ratePerSecond
  ]

  @type t :: %__MODULE__{
    :queueLength => float() | nil,
    :ratePerSecond => float() | nil
  }

  def decode(value) do
    value
  end
end

