# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BatchObjectsCreateRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :fields,
    :objects
  ]

  @type t :: %__MODULE__{
    :fields => [String.t] | nil,
    :objects => [Weaviate.Model.Object.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:objects, :list, Weaviate.Model.Object)
  end
end

