# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BatchDeleteMatch do
  @moduledoc """
  Outlines how to find the objects to be deleted.
  """

  @derive Jason.Encoder
  defstruct [
    :class,
    :where
  ]

  @type t :: %__MODULE__{
    :class => String.t | nil,
    :where => Weaviate.Model.WhereFilter.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:where, :struct, Weaviate.Model.WhereFilter)
  end
end

