# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BatchDelete do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :match,
    :output,
    :dryRun
  ]

  @type t :: %__MODULE__{
    :match => Weaviate.Model.BatchDeleteMatch.t | nil,
    :output => String.t | nil,
    :dryRun => boolean() | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:match, :struct, Weaviate.Model.BatchDeleteMatch)
  end
end

