# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BatchDeleteResponse do
  @moduledoc """
  Delete Objects response.
  """

  @derive Jason.Encoder
  defstruct [
    :match,
    :output,
    :dryRun,
    :results
  ]

  @type t :: %__MODULE__{
    :match => Weaviate.Model.BatchDeleteMatch.t | nil,
    :output => String.t | nil,
    :dryRun => boolean() | nil,
    :results => Weaviate.Model.BatchDeleteResponseResults.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:match, :struct, Weaviate.Model.BatchDeleteMatch)
     |> Deserializer.deserialize(:results, :struct, Weaviate.Model.BatchDeleteResponseResults)
  end
end

