# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.BatchReferenceResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :from,
    :to,
    :tenant,
    :result
  ]

  @type t :: %__MODULE__{
    :from => String.t | nil,
    :to => String.t | nil,
    :tenant => String.t | nil,
    :result => Weaviate.Model.BatchReferenceResponseAllOfResult.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:result, :struct, Weaviate.Model.BatchReferenceResponseAllOfResult)
  end
end

