# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.C11yWordsResponse do
  @moduledoc """
  An array of available words and contexts.
  """

  @derive Jason.Encoder
  defstruct [
    :concatenatedWord,
    :individualWords
  ]

  @type t :: %__MODULE__{
    :concatenatedWord => Weaviate.Model.C11yWordsResponseConcatenatedWord.t | nil,
    :individualWords => [Weaviate.Model.C11yWordsResponseIndividualWordsInner.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:concatenatedWord, :struct, Weaviate.Model.C11yWordsResponseConcatenatedWord)
     |> Deserializer.deserialize(:individualWords, :list, Weaviate.Model.C11yWordsResponseIndividualWordsInner)
  end
end

