# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.C11yWordsResponseIndividualWordsInnerInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :vector,
    :nearestNeighbors
  ]

  @type t :: %__MODULE__{
    :vector => [float()] | nil,
    :nearestNeighbors => [Weaviate.Model.C11yNearestNeighborsInner.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:nearestNeighbors, :list, Weaviate.Model.C11yNearestNeighborsInner)
  end
end

