# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.C11yWordsResponseIndividualWordsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :word,
    :present,
    :info
  ]

  @type t :: %__MODULE__{
    :word => String.t | nil,
    :present => boolean() | nil,
    :info => Weaviate.Model.C11yWordsResponseIndividualWordsInnerInfo.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:info, :struct, Weaviate.Model.C11yWordsResponseIndividualWordsInnerInfo)
  end
end

