# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.C11yWordsResponseConcatenatedWord do
  @moduledoc """
  Weighted results for all words
  """

  @derive Jason.Encoder
  defstruct [
    :concatenatedWord,
    :singleWords,
    :concatenatedVector,
    :concatenatedNearestNeighbors
  ]

  @type t :: %__MODULE__{
    :concatenatedWord => String.t | nil,
    :singleWords => [map()] | nil,
    :concatenatedVector => [float()] | nil,
    :concatenatedNearestNeighbors => [Weaviate.Model.C11yNearestNeighborsInner.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:concatenatedNearestNeighbors, :list, Weaviate.Model.C11yNearestNeighborsInner)
  end
end

