# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.C11yVectorBasedQuestionInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :classVectors,
    :classProps
  ]

  @type t :: %__MODULE__{
    :classVectors => [float()] | nil,
    :classProps => [Weaviate.Model.C11yVectorBasedQuestionInnerClassPropsInner.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:classProps, :list, Weaviate.Model.C11yVectorBasedQuestionInnerClassPropsInner)
  end
end

