# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.C11yExtension do
  @moduledoc """
  A resource describing an extension to the contextinoary, containing both the identifier and the definition of the extension
  """

  @derive Jason.Encoder
  defstruct [
    :concept,
    :definition,
    :weight
  ]

  @type t :: %__MODULE__{
    :concept => String.t | nil,
    :definition => String.t | nil,
    :weight => float() | nil
  }

  def decode(value) do
    value
  end
end

