# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.ClassificationMeta do
  @moduledoc """
  Additional information to a specific classification
  """

  @derive Jason.Encoder
  defstruct [
    :started,
    :completed,
    :count,
    :countSucceeded,
    :countFailed
  ]

  @type t :: %__MODULE__{
    :started => DateTime.t | nil,
    :completed => DateTime.t | nil,
    :count => integer() | nil,
    :countSucceeded => integer() | nil,
    :countFailed => integer() | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:started, :datetime, nil)
     |> Deserializer.deserialize(:completed, :datetime, nil)
  end
end

