# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.Classification do
  @moduledoc """
  Manage classifications, trigger them and view status of past classifications.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :class,
    :classifyProperties,
    :basedOnProperties,
    :status,
    :meta,
    :type,
    :settings,
    :error,
    :filters
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :class => String.t | nil,
    :classifyProperties => [String.t] | nil,
    :basedOnProperties => [String.t] | nil,
    :status => String.t | nil,
    :meta => Weaviate.Model.ClassificationMeta.t | nil,
    :type => String.t | nil,
    :settings => map() | nil,
    :error => String.t | nil,
    :filters => Weaviate.Model.ClassificationFilters.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:meta, :struct, Weaviate.Model.ClassificationMeta)
     |> Deserializer.deserialize(:filters, :struct, Weaviate.Model.ClassificationFilters)
  end
end

