# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.Deprecation do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :status,
    :apiType,
    :msg,
    :mitigation,
    :sinceVersion,
    :plannedRemovalVersion,
    :removedIn,
    :removedTime,
    :sinceTime,
    :locations
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :status => String.t | nil,
    :apiType => String.t | nil,
    :msg => String.t | nil,
    :mitigation => String.t | nil,
    :sinceVersion => String.t | nil,
    :plannedRemovalVersion => String.t | nil,
    :removedIn => String.t | nil,
    :removedTime => DateTime.t | nil,
    :sinceTime => DateTime.t | nil,
    :locations => [String.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:removedTime, :datetime, nil)
     |> Deserializer.deserialize(:sinceTime, :datetime, nil)
  end
end

