# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.ErrorResponse do
  @moduledoc """
  An error response given by Weaviate end-points.
  """

  @derive Jason.Encoder
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
    :error => [Weaviate.Model.ErrorResponseErrorInner.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:error, :list, Weaviate.Model.ErrorResponseErrorInner)
  end
end

