# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.GeoCoordinates do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :latitude,
    :longitude
  ]

  @type t :: %__MODULE__{
    :latitude => float() | nil,
    :longitude => float() | nil
  }

  def decode(value) do
    value
  end
end

