# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.GraphQlError do
  @moduledoc """
  An error response caused by a GraphQL query.
  """

  @derive Jason.Encoder
  defstruct [
    :locations,
    :message,
    :path
  ]

  @type t :: %__MODULE__{
    :locations => [Weaviate.Model.GraphQlErrorLocationsInner.t] | nil,
    :message => String.t | nil,
    :path => [String.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:locations, :list, Weaviate.Model.GraphQlErrorLocationsInner)
  end
end

