# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.GraphQlErrorLocationsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :column,
    :line
  ]

  @type t :: %__MODULE__{
    :column => integer() | nil,
    :line => integer() | nil
  }

  def decode(value) do
    value
  end
end

