# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.GraphQlResponse do
  @moduledoc """
  GraphQL based response: http://facebook.github.io/graphql/.
  """

  @derive Jason.Encoder
  defstruct [
    :data,
    :errors
  ]

  @type t :: %__MODULE__{
    :data => %{optional(String.t) => Weaviate.Model.Map.t} | nil,
    :errors => [Weaviate.Model.GraphQlError.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:errors, :list, Weaviate.Model.GraphQlError)
  end
end

