# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.GraphQlQuery do
  @moduledoc """
  GraphQL query based on: http://facebook.github.io/graphql/.
  """

  @derive Jason.Encoder
  defstruct [
    :operationName,
    :query,
    :variables
  ]

  @type t :: %__MODULE__{
    :operationName => String.t | nil,
    :query => String.t | nil,
    :variables => map() | nil
  }

  def decode(value) do
    value
  end
end

