# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.InvertedIndexConfig do
  @moduledoc """
  Configure the inverted index built into Weaviate
  """

  @derive Jason.Encoder
  defstruct [
    :cleanupIntervalSeconds,
    :bm25,
    :stopwords,
    :indexTimestamps,
    :indexNullState,
    :indexPropertyLength
  ]

  @type t :: %__MODULE__{
    :cleanupIntervalSeconds => float() | nil,
    :bm25 => Weaviate.Model.Bm25Config.t | nil,
    :stopwords => Weaviate.Model.StopwordConfig.t | nil,
    :indexTimestamps => boolean() | nil,
    :indexNullState => boolean() | nil,
    :indexPropertyLength => boolean() | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:bm25, :struct, Weaviate.Model.Bm25Config)
     |> Deserializer.deserialize(:stopwords, :struct, Weaviate.Model.StopwordConfig)
  end
end

