# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.Link do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :href,
    :rel,
    :name,
    :documentationHref
  ]

  @type t :: %__MODULE__{
    :href => String.t | nil,
    :rel => String.t | nil,
    :name => String.t | nil,
    :documentationHref => String.t | nil
  }

  def decode(value) do
    value
  end
end

