# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.MultiTenancyConfig do
  @moduledoc """
  Configuration related to multi-tenancy within a class
  """

  @derive Jason.Encoder
  defstruct [
    :enabled
  ]

  @type t :: %__MODULE__{
    :enabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

