# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.NodesStatusResponse do
  @moduledoc """
  The status of all of the Weaviate nodes
  """

  @derive Jason.Encoder
  defstruct [
    :nodes
  ]

  @type t :: %__MODULE__{
    :nodes => [Weaviate.Model.NodeStatus.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:nodes, :list, Weaviate.Model.NodeStatus)
  end
end

