# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.PatchDocumentAction do
  @moduledoc """
  Either a JSONPatch document as defined by RFC 6902 (from, op, path, value), or a merge document (RFC 7396).
  """

  @derive Jason.Encoder
  defstruct [
    :from,
    :op,
    :path,
    :value,
    :merge
  ]

  @type t :: %__MODULE__{
    :from => String.t | nil,
    :op => String.t,
    :path => String.t,
    :value => map() | nil,
    :merge => Weaviate.Model.Object.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:merge, :struct, Weaviate.Model.Object)
  end
end

