# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.PeerUpdate do
  @moduledoc """
  A single peer in the network.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :uri,
    :schemaHash
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :uri => String.t | nil,
    :schemaHash => String.t | nil
  }

  def decode(value) do
    value
  end
end

