# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.Principal do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :username,
    :groups
  ]

  @type t :: %__MODULE__{
    :username => String.t | nil,
    :groups => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

