# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.ReferenceMetaClassification do
  @moduledoc """
  This meta field contains additional info about the classified reference property
  """

  @derive Jason.Encoder
  defstruct [
    :overallCount,
    :winningCount,
    :losingCount,
    :closestOverallDistance,
    :winningDistance,
    :meanWinningDistance,
    :closestWinningDistance,
    :closestLosingDistance,
    :losingDistance,
    :meanLosingDistance
  ]

  @type t :: %__MODULE__{
    :overallCount => float() | nil,
    :winningCount => float() | nil,
    :losingCount => float() | nil,
    :closestOverallDistance => float() | nil,
    :winningDistance => float() | nil,
    :meanWinningDistance => float() | nil,
    :closestWinningDistance => float() | nil,
    :closestLosingDistance => float() | nil,
    :losingDistance => float() | nil,
    :meanLosingDistance => float() | nil
  }

  def decode(value) do
    value
  end
end

