# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.ReplicationConfig do
  @moduledoc """
  Configure how replication is executed in a cluster
  """

  @derive Jason.Encoder
  defstruct [
    :factor
  ]

  @type t :: %__MODULE__{
    :factor => integer() | nil
  }

  def decode(value) do
    value
  end
end

