# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.SchemaClusterStatus do
  @moduledoc """
  Indicates the health of the schema in a cluster.
  """

  @derive Jason.Encoder
  defstruct [
    :healthy,
    :error,
    :hostname,
    :nodeCount,
    :ignoreSchemaSync
  ]

  @type t :: %__MODULE__{
    :healthy => boolean() | nil,
    :error => String.t | nil,
    :hostname => String.t | nil,
    :nodeCount => float() | nil,
    :ignoreSchemaSync => boolean() | nil
  }

  def decode(value) do
    value
  end
end

