# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.ShardStatusGetResponse do
  @moduledoc """
  Response body of shard status get request
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :status,
    :vectorQueueSize
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :status => String.t | nil,
    :vectorQueueSize => integer() | nil
  }

  def decode(value) do
    value
  end
end

