# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.ShardStatus do
  @moduledoc """
  The status of a single shard
  """

  @derive Jason.Encoder
  defstruct [
    :status
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil
  }

  def decode(value) do
    value
  end
end

