# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.SingleRef do
  @moduledoc """
  Either set beacon (direct reference) or set class and schema (concept reference)
  """

  @derive Jason.Encoder
  defstruct [
    :class,
    :schema,
    :beacon,
    :href,
    :classification
  ]

  @type t :: %__MODULE__{
    :class => String.t | nil,
    :schema => map() | nil,
    :beacon => String.t | nil,
    :href => String.t | nil,
    :classification => Weaviate.Model.ReferenceMetaClassification.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:classification, :struct, Weaviate.Model.ReferenceMetaClassification)
  end
end

