# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.StopwordConfig do
  @moduledoc """
  fine-grained control over stopword list usage
  """

  @derive Jason.Encoder
  defstruct [
    :preset,
    :additions,
    :removals
  ]

  @type t :: %__MODULE__{
    :preset => String.t | nil,
    :additions => [String.t] | nil,
    :removals => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

