# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.Tenant do
  @moduledoc """
  attributes representing a single tenant within weaviate
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :activityStatus
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :activityStatus => String.t | nil
  }

  def decode(value) do
    value
  end
end

