# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.WeaviateRoot200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :links
  ]

  @type t :: %__MODULE__{
    :links => [Weaviate.Model.Link.t] | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:links, :list, Weaviate.Model.Link)
  end
end

