# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.WhereFilterGeoRange do
  @moduledoc """
  filter within a distance of a georange
  """

  @derive Jason.Encoder
  defstruct [
    :geoCoordinates,
    :distance
  ]

  @type t :: %__MODULE__{
    :geoCoordinates => Weaviate.Model.GeoCoordinates.t | nil,
    :distance => Weaviate.Model.WhereFilterGeoRangeDistance.t | nil
  }

  alias Weaviate.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:geoCoordinates, :struct, Weaviate.Model.GeoCoordinates)
     |> Deserializer.deserialize(:distance, :struct, Weaviate.Model.WhereFilterGeoRangeDistance)
  end
end

