# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Model.WhereFilterGeoRangeDistance do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :max
  ]

  @type t :: %__MODULE__{
    :max => float() | nil
  }

  def decode(value) do
    value
  end
end

