# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Api.Discovery do
  @moduledoc """
  API calls for all endpoints tagged `Discovery`.
  """

  alias Weaviate.Connection
  import Weaviate.RequestBuilder

  @doc """
  OIDC discovery information if OIDC auth is enabled
  OIDC Discovery page, redirects to the token issuer if one is configured

  ### Parameters

  - `connection` (Weaviate.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Weaviate.Model.WellKnownOpenidConfigurationGet200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec well_known_openid_configuration_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, Weaviate.Model.WellKnownOpenidConfigurationGet200Response.t} | {:ok, Weaviate.Model.ErrorResponse.t} | {:error, Tesla.Env.t}
  def well_known_openid_configuration_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/.well-known/openid-configuration")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Weaviate.Model.WellKnownOpenidConfigurationGet200Response},
      {404, false},
      {500, Weaviate.Model.ErrorResponse}
    ])
  end
end
