# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Weaviate.Api.Meta do
  @moduledoc """
  API calls for all endpoints tagged `Meta`.
  """

  alias Weaviate.Connection
  import Weaviate.RequestBuilder

  @doc """
  Returns meta information of the current Weaviate instance.
  Gives meta information about the server and can be used to provide information to another Weaviate instance that wants to interact with the current instance.

  ### Parameters

  - `connection` (Weaviate.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Weaviate.Model.Meta.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec meta_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, Weaviate.Model.ErrorResponse.t} | {:ok, Weaviate.Model.Meta.t} | {:error, Tesla.Env.t}
  def meta_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/meta")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Weaviate.Model.Meta},
      {401, false},
      {403, Weaviate.Model.ErrorResponse},
      {500, Weaviate.Model.ErrorResponse}
    ])
  end
end
